#############################################################
##
## WARNING: DEFAULT CONFIGURATION - tiogo won't work like this!
##
## AccessKey and SecretKey must be set to access Tenable.io
#############################################################
VM:
  BaseURL: http://localhost:10101
  AccessKey: ak1,ak2
  SecretKey: sk1,sk2

Server:
  BaseURL: https://cloud.tenable.com
